CREATE TABLE BESTELLUNGEN(
    ID INT NOT NULL AUTO_INCREMENT,
    BENUTZER INT DEFAULT 0,
    NUMMER VARCHAR(10) NOT NULL,
    DATUM DATETIME DEFAULT CURRENT_TIMESTAMP, 
    PREIS DECIMAL(10,2) DEFAULT 0,
    INHALT TEXT NOT NULL, 
    PRIMARY KEY(ID),
    FOREIGN KEY(BENUTZER) REFERENCES BENUTZER(ID)
);
